[package]
name = "snake-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termren = { git = "https://github.com/Stuff7/termren", branch = "master" }
